/**
 * @description       :
 * @author            : Swastik Dan
 * @group             :
 * @last modified on  : 09-20-2024
 * @last modified by  : Swastik Dan
 * @history           :
 **/
//https://stackoverflow.com/questions/6942624/how-can-i-throw-a-general-exception-in-java
public class CandidateTriggerException extends Exception {
  // public WelcomeEmailTriggerHandlerException(String message) {
  //   super(message);
  // }
}