/**
 * @description       :  This is a class to store error constant values.
 * @author            : Swastik Dan
 * @group             :
 * @last modified on  : 12-20-2024
 * @last modified by  : Swastik Dan
 * @history           :
 **/
public without sharing class ErrorConstants {
  public static final String NO_NEW_RECORDS_FOUND = 'No new records found';
  public static final String NO_CANDIDATE_RECORDS_FOUND = 'No candidate records found';
  public static final String EMAIL_TEMPLATE_NOT_FOUND = 'Email template not found';
  public static final String TEST_EXCEPTION = 'Test Exception';
}
